FROM resurgentech/dev_base-ubuntu2004:latest

RUN apt-get update --fix-missing && \
    apt install -y software-properties-common && \
    apt install -y ansible && \
    apt install -y sshpass && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY docker_image_history.* /etc
