FROM resurgentech/kernel_build-amazonlinux2:latest

RUN yum clean all && \
    yum update -y && \
    yum install -y wget \
                   openssl-devel && \
    yum remove -y cmake && \
    yum install -y qt5-qtbase-devel && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN cd /tmp; \
    wget https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz; \
    tar xf cmake-3.23.2-linux-x86_64.tar.gz; \
    cp -r /tmp/cmake-3.23.2-linux-x86_64/bin/* /usr/bin/; \
    cp -r /tmp/cmake-3.23.2-linux-x86_64/share/* /usr/share/; \
    cp -r /tmp/cmake-3.23.2-linux-x86_64/man/* /usr/share/man/; \
    cp -r /tmp/cmake-3.23.2-linux-x86_64/doc/* /usr/share/doc/; \
    rm -f cmake-3.23.2-linux-x86_64.tar.gz; \
    rm -rf cmake-3.23.2-linux-x86_64;

COPY docker_image_history.* /etc
