FROM resurgentech/kernel_build-ubuntu2204:latest

RUN apt-get update --fix-missing && \
    apt-get install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools cmake && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY docker_image_history.* /etc
