FROM resurgentech/dev_base-debian11:latest

RUN apt-get update --fix-missing && \
    apt-get install -y libncurses-dev libssl-dev libelf-dev libudev-dev \
                       libpci-dev libiberty-dev equivs dwarves && \
    apt-get install -y dkms && \
    DEBIAN_FRONTEND=noninteractive apt-get build-dep -y linux && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY docker_image_history.* /etc
