FROM resurgentech/base-amazonlinux2:latest

RUN yum clean all && \
    yum update -y && \
    yum groupinstall -y "Development Tools" && \
    yum install -y  bc \
                    newt \
                    slang \
                    xmlto \
                    rsync \
                    cmake \
                    net-tools \
                    rpm-build \
                    dpkg-dev \
                    zstd \
                    && \
    yum clean all && \
    rm -rf /var/cache/yum

COPY docker_image_history.* /etc
