FROM resurgentech/base-popos2004:latest

RUN apt-get update --fix-missing && \
    apt-get install -y build-essential && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y autoconf asciidoc bc bison flex gawk gettext git gzip \
                       hostname m4 net-tools openssl rsync xmlto rpm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY docker_image_history.* /etc
