FROM resurgentech/base-fedora36:latest

RUN dnf groupinstall -y "Development Tools" && \
    dnf install -y  bc \
                    newt \
                    slang \
                    xmlto \
                    rsync \
                    cmake \
                    net-tools \
                    rpm-build \
                    dpkg-dev \
                    zstd \
                    && \
    dnf clean all && \
    rm -rf /var/cache/yum

COPY docker_image_history.* /etc
