FROM ubuntu:22.04

RUN apt-get update --fix-missing && \
    cp /etc/apt/sources.list /etc/apt/sources.list~ && \
    sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list && \
    apt-get update && \
    apt-get upgrade -y  --allow-downgrades && \
    rm /etc/apt/sources.list~ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY docker_image_history.* /etc
