#https://github.com/hugojosefson/docker-popos
FROM hugojosefson/popos

RUN apt-get update --fix-missing && \
    apt-get upgrade -y  --allow-downgrades && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY docker_image_history.* /etc
