FROM almalinux:8.5

RUN dnf clean all && \
    dnf update -y && \
    dnf install -y epel-release && \
    dnf install -y dnf-plugins-core && \
    dnf config-manager --set-enabled powertools && \
    rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org && \
    dnf install -y https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm && \
    dnf clean all && \
    rm -rf /var/cache/yum

COPY docker_image_history.* /etc
